version: "3"

services: 
      
  # Apache NiFi: Data Ingestion Tool
  nifi:
    image: 'apache/nifi:latest'
    hostname: nifi
    container_name: nifi
    ports:
      - '8090:8090'
    environment:
      - NIFI_WEB_HTTP_PORT=8090
      
  # Jupyter: Notebook Analytics
  jupyter:
    image: 'jupyter/pyspark-notebook:spark-2'
    hostname: jupyterPySpark
    container_name: jupyterPySpark
    user: root
    environment:
      - JUPYTER_TOKEN=edem
    volumes:
      - ./config/spark-defaults.conf:/usr/local/spark-2.4.5-bin-hadoop2.7/conf/spark-defaults.conf
    ports:
      - '8888:8888'
      
# Elasticsearch: Data Storage and Search Engine
  elasticsearch:
    image: 'elasticsearch:7.3.0'
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node   

  # Kibana: Elasticsearch Dashboarding
  kibana:
    image: 'kibana:7.3.0'
    hostname: kibana
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
    depends_on:
      - elasticsearch